### ISSUE TITLE
CCC

### ISSUE THREAD

**Issue by avi22491** [AndrewWalker/Dubins-Curves#4]
Hello, 

I am working on dubins path, and your code works great!!!. 

I wonder if your code includes CCC configuration? For any set of initial and final points, I could get only CSC configuration. If the code does include CCC configuration, please suggest some set of initial and final conditions, which results in this. 

Thanks

**Comment by AndrewWalker** [comment]
Yes, CCC configurations are produced by the code. Typically this occurs when a pair of configurations are very close together.

q_0 = (0,0,0) and q_1 = (0,0,pi) should produce the results you're looking for

**Comment by avi22491** [comment]
Hello Andrew,

Thanks for the reply,

I could produce required results, by your suggestion.

With Regards

Avinash S
